Created a Catalog page and card view.
WSU-4110/AR-Interior-Design pull request #30
Opened 2024-02-16 19:44 UTC by roryslange

Created a catalog page that displays cards for items, still needs to be connected to the back end, however, there are some placeholder values for now.

2024-02-20 00:03 UTC, Bryan-Lor commented on Unity-Project/.DS_Store
Binary file, can be left out of git. You can delete the file then do `git add` and then `git commit`

2024-02-20 00:05 UTC, Bryan-Lor requested changes
[Unity-Project/.DS_Store](https://github.com/WSU-4110/AR-Interior-Design/pull/30/files#diff-64bef8147187cde6fa88915f0b2e24e1b38705a7ed9fb263755d579b34e20302) is a binary file, we should not include this. Everything else looks good

2024-02-23 20:31 UTC, Jessku approved these changes
looks good

2024-02-27 14:42 UTC, Bryan-Lor approved these changes

2024-02-27 15:04 UTC, merged